Hashmap
dmitrysluch/hashmap pull request #1
Opened 2020-02-16 23:08 UTC by dmitrysluch

Посылка 30949299 в яндекс контесте

2020-03-15 23:14 UTC, glebshp requested changes
Пожалуйста, сделай код читаемым, с хорошими именами, отступами, пробелами, потом проверю по существу

2020-03-15 23:14 UTC, glebshp commented on hashmap.h
> +//    DO WHAT THE FUCK YOU WANT TO PUBLIC LICENSE Version 2,
Угадай, что мне нравится в этом заголовке.

2020-03-15 23:14 UTC, glebshp commented on hashmap.h
> +// c++ 14 doesn't have optional,
Здесь не хватает пустой строки

2020-03-15 23:14 UTC, glebshp commented on hashmap.h
> +  typedef std::pair<const KeyType, ValueType> PairType;
PairType - не особо удачное имя, подбери более ёмкое

2020-03-15 23:14 UTC, glebshp commented on hashmap.h
> + public:
А почему тут используется public, а перед предыдущей строкой нет?

2020-03-15 23:14 UTC, glebshp commented on hashmap.h
> +  static const size_t kInverseMinLoadFactor = 8;
static const обычно не делают private

2020-03-15 23:14 UTC, glebshp commented on hashmap.h
> +  static const size_t kInverseNormalLoadFactor = 4;
const -> constexpr

2020-03-15 23:14 UTC, glebshp commented on hashmap.h
> +  inline void insert_internal(std::vector<PointerType> *dst,
* обычно приклеивают к типу, а не к переменной, то есть int* ptr, а не int *ptr, так как ты хочешь сказать "переменная ptr типа указатель на int"

2020-03-15 23:14 UTC, glebshp commented on hashmap.h
> +    for (; (*dst)[idx]; idx = (idx + 1) % dst->size()) {
just say no

2020-03-15 23:14 UTC, glebshp commented on hashmap.h
> +    for (; table_[idx]; idx = (idx + 1) % table_.size()) {
такой for не читаем, давай он хотя бы станет while

2020-03-15 23:14 UTC, glebshp commented on hashmap.h
> +  void rehash(size_t new_capacity) {
отступ

2020-03-17 19:46 UTC, dmitrysluch commented
Ссылка на посылку: [31595394](https://official.contest.yandex.ru/contest/17022/run-report/31595394/)

2020-05-31 00:29 UTC, glebshp requested changes

2020-05-31 00:29 UTC, glebshp commented on hashmap.h
> +  // Constructs hash map from std::initializer_list
Добавить точки в конец всех комментариев

2020-05-31 00:29 UTC, glebshp commented on hashmap.h
> +    list_.clear();  // Can't assing list because keys stored in list are marked
Это будет нормально смотреться комментарием перед строкой

2020-05-31 00:29 UTC, glebshp commented on hashmap.h
> +    if (&other == this)
скобки

2020-05-31 00:29 UTC, glebshp commented on hashmap.h
> +  // exception if the dey doesn't exists. Average time complexity O(1).
Не Average, а expected

2020-05-31 00:29 UTC, glebshp commented on hashmap.h
> +  void recover_chains(size_t deleted) {
Это, наверное, самая сложная логика в этом классе, следует снабдить её более подробным описанием

2020-05-31 00:29 UTC, glebshp commented on hashmap.h
> +    if (table_.size() < 1UL || table_.size() < kInverseMaxLoadFactor * size_ ||
Здесь написаны разные по смыслу условия "перехешируй если слишком много" и "перехешируй если слишком мало", следует разнести их на разные If-ы

2020-05-31 11:46 UTC, dmitrysluch commented
[Посылка 33326716](https://official.contest.yandex.ru/contest/17022/run-report/33326716/)

2020-06-09 20:34 UTC, glebshp requested changes
По коду ОК, но меня волнует вопрос про корректность и асимптотику схемы удаления

2020-06-09 20:34 UTC, glebshp commented on hashmap.h
> +    while (table_[i].has_value()) {
Какое-то оригинальное решение, первый раз такое вижу, ты это стресс-тестировал на корректность, доказывал асимптотику?

2020-06-19 22:07 UTC, glebshp approved these changes

2020-06-20 06:05 UTC, merged